create database college_db;
use college_db;
create table student(id int primary key auto_increment,name varchar(50),dept varchar(50),marks int );
show tables;
insert into student(name,dept,marks) values ("sony","cse",90),("sri","ece",89),("reetu","mech",78);
select * from student;
update student set marks=72 where id=2;
select * from student;
delete from student where id=3;
select * from student where dept <> "cse";
select * from student where dept="cse" and marks>70;
select * from student where dept="cse" or dept="ece";
select * from student where not dept="cse";
SELECT * FROM student ORDER BY marks ASC;
SELECT * FROM student ORDER BY marks DESC;
SELECT dept, COUNT(*) FROM student GROUP BY dept;
SELECT MIN(marks) FROM student;
SELECT MAX(marks) FROM student;
SELECT AVG(marks) FROM student;
SELECT COUNT(*) FROM student;
SELECT * FROM student WHERE name LIKE 's%';
SELECT * FROM student WHERE name LIKE '%i';
SELECT * FROM student WHERE name LIKE '%r%';